defaults:
  - _self_
  - experiment: null

data:
  name: CoLa
  dataset:
    _target_: src.dataset.sequence_classification.${data.name}
  max_length: 128
  llm_batch_size: 16
  smooth_head_batch_size: 128
  num_workers: 0
model:
  torch_dtype:
    _target_: hydra.utils.get_object
    path: torch.bfloat16
  num_labels: 0
adapter:
  path: ${oc.env:PROJECT_ROOT}/data/models/${model_name}_runs_seeds/${data.name}/${seed}/
save_dir: ${oc.env:PROJECT_ROOT}/baseline_eval_seeds/results/${model_name}_results_ds_${train_on_dataset}
train_on_dataset: train
extract_features:
  layer_number: -1
normalization: true
rde_n_components:
  - 256
