_target_: src.model.llm_module.LLMLitModule
_recursive_: false
model:
  _target_: src.utils.instantiators.PreTrainedModelInstantiate
  pretrained_path: ${base_architecture}
  torch_dtype:
    _target_: hydra.utils.get_object
    path: torch.bfloat16
  num_labels: ${data.num_labels}
optimize_metric_name: ${optimize_metric_name}
optimize_metric_mode: ${optimize_metric_mode}

optimizer:
  _target_: torch.optim.AdamW
  lr: 5e-5
  weight_decay: 1e-1


scheduler: ${scheduler}
