_target_: src.model.llm_module.LLMLitModule
_recursive_: false
model:
  _target_: src.utils.instantiators.PeftModelInstantiate
  _recursive_: false
  model:
    _target_: transformers.AutoModelForSequenceClassification.from_pretrained
    pretrained_model_name_or_path: ${base_architecture}
    torch_dtype:
      _target_: hydra.utils.get_object
      path: torch.bfloat16
    num_labels: ${data.num_labels}
  peft_config: ${adapter}
optimize_metric_name: ${optimize_metric_name}
optimize_metric_mode: ${optimize_metric_mode}

optimizer:
  _target_: torch.optim.AdamW
  lr: 5e-5
  weight_decay: 1e-1


scheduler: ${scheduler}
