- _target_: src.uncertainty.metrics.ROCAUCUEMetric
  ue_estimator_field: max_prob
  prediction_field: predictions
  target_field: label_ids
- _target_: src.uncertainty.metrics.ROCAUCUEMetric
  ue_estimator_field: variance
  prediction_field: predictions
  target_field: label_ids
- _target_: src.uncertainty.metrics.RocAUCMetric
  prediction_field: predictions
  target_field: label_ids
- _target_: src.uncertainty.metrics.RCAUCMetric
  ue_estimator_field: max_prob
  prediction_field: predictions
  target_field: label_ids
- _target_: src.uncertainty.metrics.Accuracy
  prediction_field: predictions
  target_field: label_ids
- _target_: src.uncertainty.metrics.ExpectedCalibrationError
  prediction_field: predictions
  target_field: label_ids
#- _target_: src.uncertainty.metrics.RocAUCMetric
#  prediction_field: ensemble_variance
#  target_field: label_ids
- _target_: src.uncertainty.metrics.RCAUCMetric
  ue_estimator_field: variance
  prediction_field: predictions
  target_field: label_ids