learning_rates: [1e-8,0.0]
epoch_candidates: [30]
lambda_candidates: [100.0]
reg_alpha_candidates:  [0.0]
reg_l2sp_candidates: [0.0]
extract_features_layer_number: [-1]
load_weights: ['cls_head']
name: debug