learning_rates: [4e-4]
epoch_candidates: [20]
lambda_candidates: [100.0]
reg_alpha_candidates: [0.01, 0.1, 1.0]
reg_l2sp_candidates: [0.01, 0.1, 1.0]
extract_features_layer_number: [-1]
load_weights: ['cls_head']
head_type: ['entropy']
name: entropy_response_finetune