learning_rates: [1e-4, 1e-5]
epoch_candidates: [10]
lambda_candidates: [100.0]
reg_alpha_candidates: [0.0, 5, 10]
reg_l2sp_candidates: [0.0, 5, 10]
extract_features_layer_number: [-1]
load_weights: ['cls_head']
name: full_wo_epoch