learning_rates: [4e-4, 1e-4, 1e-5]
epoch_candidates: [20]
lambda_candidates: [100.0]
reg_alpha_candidates: [0.0]
reg_l2sp_candidates: [0.0]
extract_features_layer_number: [-1]
load_weights: ['linear_random']
head_type: ['sr']
name: ablation_softmax_response_finetune_bce_only_linear_random