learning_rates: [3e-4, 1e-4, 7e-4]
epoch_candidates: [20]
lambda_candidates: [100.0]
reg_alpha_candidates: [0.01, 0.1]
reg_l2sp_candidates: [0.01, 0.1]
extract_features_layer_number: [-1]
load_weights: ['cls_head']
head_type: ['sr']
name: softmax_response_finetune