defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: ${optimize_metric_name}
  mode: ${optimize_metric_mode}
  save_last: True
  save_top_k: -1
  auto_insert_metric_name: False
  save_weights_only: false

model_summary:
  max_depth: 2

safe_peft_model:
  _target_: src.utils.callbacks.SavePeftModel

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
